"""0005_add_telegram_id_table_support_chat

Revision ID: 038d634bcb23
Revises: 188ac349b616
Create Date: 2026-08-28 17:45:53.054855

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "038d634bcb23"
down_revision: str | None = "188ac349b616"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "support_chats", sa.Column("telegram_id", sa.BigInteger(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("support_chats", "telegram_id")
    # ### end Alembic commands ###
